cat <<EOF > .env
DATABASE_URL=$DATABASE_URL
ACCESS_SECRET=$ACCESS_SECRET
REFRESH_SECRET=$REFRESH_SECRET
API_KEY=$API_KEY
AUTH_DOMAIN=$AUTH_DOMAIN
PROJECT_ID=$PROJECT_ID
STORAGE_BUCKET=$STORAGE_BUCKET
MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
APP_ID=$APP_ID
MEASUREMENT_ID=$MEASUREMENT_ID
EOF
